{
  "comments": [
    {
      "key": {
        "uuid": "fa963961_d7b5be7e",
        "filename": "python-congress-tests-tempest.spec",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 113
      },
      "writtenOn": "2018-01-12T14:09:46Z",
      "side": 1,
      "message": "Is there any reason why the python3 subpackage is disabled in Fedora? If so, let\u0027s add a comment explaining it.",
      "range": {
        "startLine": 9,
        "startChar": 0,
        "endLine": 9,
        "endChar": 22
      },
      "revId": "82c3588a364018ba5d3f7c6e3e8c8fc1552dc176",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}